apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
        ports:
        - containerPort: {{ .Values.app.targetPort }}

  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Values.traffic.virtualservice.name }}
            routes:
            - http
          destinationRule:
            name: {{ .Values.traffic.destinationrule.name }}
            stableSubsetName: stable
            canarySubsetName: canary

      steps:
      {{- range .Values.argo.rollout.steps }}
        - setWeight: {{ .weight }}
        {{- if .pause }}
        - pause: 
            duration: {{ .pause }}
        {{- end }}
      {{- end }}