apiVersion: v2
name: gitops
version: 0.1.0

dependencies:
  - name: argo
    version: 0.1.0
    repository: "file://charts/argo"

  # - name: canary-traffic
  #   version: 0.1.0
  #   repository: "file://charts/canary-traffic"