apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.gateway.name }}

spec:
  selector:
    istio: {{ .Values.global.gateway.spec.selector.istio }}

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
