apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.traffic.destinationrule.name}}
spec:
  host: {{ .Values.traffic.service.name }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary