apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.canary-traffic.virtualservice.name}}
spec:
  hosts:
  - myapp.example.com
  gateways:
  - myapp-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.canary-traffic.service.name }}
        subset: stable
      weight: 100
    - destination:
        host: {{ .Values.canary-traffic.service.name }}
        subset: canary
      weight: 0